/**
 * The counters at the top of the dashboard.
 *
 * Pure, and separated from the UI on purpose: every number here is a definition
 * the couple will plan food and seating against, and a definition is worth
 * being able to read on its own without a table renderer wrapped around it.
 *
 * The distinction that matters throughout: an *entry* is one reply, a *person*
 * is a head. One entry with three companions is one entry and four people. Any
 * counter that says "people" sums `party_size` (a generated column: 1 + the
 * length of `companions`); any counter that says "entries" counts rows.
 */
import type { Rsvp } from '../supabase';

export type Stats = {
  /** Heads at the Mass, not replies. */
  massPeople: number;
  /** Heads at the Reception, not replies. */
  receptionPeople: number;
  /** Replies where both answers were no. */
  notComingEntries: number;
  /**
   * Distinct heads expected at *something*.
   *
   * Deliberately not `massPeople + receptionPeople`, which double-counts
   * everyone attending both — that sum is larger than the guest list and means
   * nothing. Also deliberately not the sum over every row, which would count
   * the people who declined. It is the sum over rows attending at least one
   * event, which is the number of humans who will actually be somewhere.
   */
  totalPeople: number;
  /** Companions marked `child` (under 12), across every reply. */
  children: number;
  /** Replies whose `created_at` falls on today's local date. */
  todayEntries: number;
};

const isComing = (r: Rsvp) => r.attending_mass || r.attending_reception;

/** Local calendar day, not UTC — "today" means today where the couple is. */
const sameLocalDay = (a: Date, b: Date) =>
  a.getFullYear() === b.getFullYear() &&
  a.getMonth() === b.getMonth() &&
  a.getDate() === b.getDate();

export function computeStats(rows: readonly Rsvp[], now: Date = new Date()): Stats {
  const stats: Stats = {
    massPeople: 0,
    receptionPeople: 0,
    notComingEntries: 0,
    totalPeople: 0,
    children: 0,
    todayEntries: 0,
  };

  for (const row of rows) {
    /* `party_size` is generated by the database, but a row can reach here from
       an optimistic edit that has not round-tripped yet, so fall back to
       computing it the same way the generated column does. */
    const size = row.party_size ?? 1 + (row.companions?.length ?? 0);

    if (row.attending_mass) stats.massPeople += size;
    if (row.attending_reception) stats.receptionPeople += size;
    if (isComing(row)) stats.totalPeople += size;
    else stats.notComingEntries += 1;

    for (const companion of row.companions ?? []) {
      if (companion.type === 'child') stats.children += 1;
    }

    if (sameLocalDay(new Date(row.created_at), now)) stats.todayEntries += 1;
  }

  return stats;
}

/**
 * Every `phone_normalised` held by more than one reply.
 *
 * Reported, never acted on. Two people in one household share a phone all the
 * time, and a wedding guest list is exactly where that happens — so this marks
 * rows for a human to glance at and nothing else. Merging or blocking on it
 * would silently lose a real reply.
 */
export function duplicatePhones(rows: readonly Rsvp[]): Set<string> {
  const seen = new Map<string, number>();
  for (const row of rows) {
    const key = row.phone_normalised;
    if (!key) continue;
    seen.set(key, (seen.get(key) ?? 0) + 1);
  }
  const duplicates = new Set<string>();
  for (const [key, count] of seen) if (count > 1) duplicates.add(key);
  return duplicates;
}
